### ISSUE TITLE
hello~ how can i get taobao app_key~?

### ISSUE THREAD

**Issue by ysw1206** [flc1125/taobao-open-api#1]
您好~  flc1125

我是一名在韩国开发淘宝 Open Api 的开发者。

在搜索过程中偶然看见您发布的 Open Source 对我有很大的帮助。

https://github.com/flc1125/taobao-open-api

对于您的 Open Source 我想询问几个问题。

1.怎样可以获得  app_key / secret_key。

2.如果可以的话能共享一下您现在所用的的这两个 Key 吗？

我再淘宝开发平台上 按照 Guide 试了好几次都没有申请成功 API 使用权限

因此特请您帮助我一下~~

谢谢~~

**Comment by flc1125** [comment]
- 你好，app_key和secret_key在http://open.taobao.com/；
- 请登录后，进入**[控制台]**可创建应用！
- 左侧的**[已获得]**，是你目前可创建的应用类型- 可根据你自己的需求，创建相关应用，创建后，对应就有app_key和secret_key；
- 每种应用，对应的API接口权限不一致，在创建应用后，在应用管理可以看到当前应用可使用的API接口

> 分享我目前所用的key，这点抱歉。暂时无法提供。
> 
> 感谢使用！

@flc1125

**Comment by ysw1206** [comment]
那我再询问一下问题：
1.我想使用有关商品 登陆，修改，删除等的 API ，申请权限的时候涉及到 PRD，和MRD 您那里能给提供一下相关模板吗？或者有没有不用这两个文档能申请API 的方法？

**Comment by flc1125** [comment]
PRD,MRD??

具体申请的规则，要按淘宝开放平台来申请了，这块业务你可以咨询下淘宝开放平台的客服！

**Comment by ysw1206** [comment]
那您最初以开发者身份申请的时候拥有的权限是 Alibaba Sourcing ISV 是这个对吗？然后再根据具体的内容在淘宝提供的应用标签来里进行选择是吗？

**Comment by flc1125** [comment]
我的应用标签是：联盟合作网站！

如果要开发更高权限的，最好用企业资质去申请。可创建的应用类型会更多！个人开发者身份，权限很低！
