### ISSUE TITLE
淘宝 appkey及appsecret申请方法

### ISSUE THREAD

**Issue by flc1125** [flc1125/taobao-open-api#2]
## 访问并登录

http://open.taobao.com/

> 若无账号，请点此注册：http://reg.taobao.com/member/newbie.htm?spm=a2107.1.0.0.vont4H&from=login

## 进入控制台

![1](https://cloud.githubusercontent.com/assets/14297703/23647136/34e933a0-034f-11e7-9531-8a684624b945.png)

## 创建应用

![2](https://cloud.githubusercontent.com/assets/14297703/23647204/8883d09c-034f-11e7-84bc-4b18458285cf.png)

## 选择应用类型

![3](https://cloud.githubusercontent.com/assets/14297703/23647227/acb2c810-034f-11e7-9b3f-1a64ef3fd88c.png)

> 应用必须是已拥有的才可创建，无权限的。一般为用户类型（个人或企业）、网站等信息问题，可根据官方流程申请

## 信息填写

> 每种不同类型的应用，信息填写均不一致，此处不作展示。

**Comment by mega94** [comment]
To me, to create an agent site, I need example: http://tb.openchinacart.com/index.php?route=common/home

**Comment by flc1125** [comment]
http://club.alimama.com/read.php?tid=6306396&ds=1&page=1&toread=1#tpc&appTag=6

**Comment by mega94** [comment]
And there is some good article, from scratch to get a clean token, I postorayust translate into another language for foreigners

**Comment by indotronic** [comment]
alipay need verifications.. :(

**Comment by mega94** [comment]
I have an alipay

**Comment by indotronic** [comment]
how to get approved alipay?

**Comment by flc1125** [comment]
https://www.alipay.com/

![image](https://cloud.githubusercontent.com/assets/14297703/24002929/f769faaa-0a9c-11e7-8335-1d220eec13d8.png)

Developer:
https://b.alipay.com/?ynsrc=zhuzhanA

PC-api:
https://b.alipay.com/signing/productDetail.htm?productId=I1011000290000001000

Mobile-api:
https://b.alipay.com/signing/productDetail.htm?productId=I1011000290000001000

**Comment by indotronic** [comment]
can you developt wordpress plugin? get product taobao? i dont have time to developt

**Comment by indotronic** [comment]
![image](https://cloud.githubusercontent.com/assets/12272248/24004075/efdbb5da-0a97-11e7-866f-9967693ea2f2.png)
because i am not chinese..

**Comment by mega94** [comment]
We just need a token, there is no explanatory article in English?

**Comment by huudepzai** [comment]
hi. i have a Business account taobao but i can't open app. because it speak is i can't create PRD to approval
. can i help me? and i want get detail product, search product with seller, keyword.Do i need any app?
[https://imgur.com/a/ov6h9](url)

**Comment by 5U5L** [comment]
叶子坑，您好.我下载了您提供的淘宝API文件。但是调用数据时失败了。您能分享下您在http://taobao.flc.ren/ 里的源文件吗？不胜感激。我的邮箱是363175812@qq.com。

**Comment by 5U5L** [comment]
我使用的DEDE cms 该如何布置代码呢？
